export const LOAD_TODO = {
  PENDING: "LOAD_TODO_PENDING",
  SUCCESS: "LOAD_TODO_SUCCESS",
  REJECTED: "LOAD_TODO_REJECTED"
};

export const TOGGLE_TODO = {
  PENDING: "TOGGLE_TODO_PENDING",
  SUCCESS: "TOGGLE_TODO_SUCCESS",
  REJECTED: "TOGGLE_TODO_REJECTED"
};
